#!/bin/sh

battery_percentage_path="/sys/class/power_supply/BAT0/capacity"
battery_status_path="/sys/class/power_supply/BAT0/status"

icons_battery=("󰂃" "󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹")
icons_battery_charging=("󰢟" "󰢜" "󰂆" "󰂇" "󰂈" "󰢝" "󰂉" "󰢞" "󰂊" "󰂋" "󰂅")

battery_percentage=$(cat "$battery_percentage_path")
battery_status=$(cat "$battery_status_path")

if [ "$battery_status" = "Charging" ]; then
   echo "${icons_battery_charging[$battery_percentage / 10]}"
else
    echo "${icons_battery[$battery_percentage / 10]}"
fi