#!/bin/sh

battery_path="/sys/class/power_supply/BAT0/capacity"

if [ -f "$battery_path" ]; then
    battery=$(cat "$battery_path")
    if [ "$battery" -le 30 ]; then
        text="🪫 $battery%"
    else
        text="🔋$battery%"
    fi
else
    text="N/A"
fi

echo $text